services:

    embanet-woocommerce-reporting-apis:

        container_name: embanet-woocommerce-reporting-apis
        
        image: softwareshinobi/embanet-woocommerce-reporting-apis

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: unless-stopped

        ports:

            - "8888:8888"

        environment:

            DB_HOST: embanet-woocommerce-reporting-apis-database

            DB_NAME: valorant_digital_workspace

            DB_USER: valorant_digital_workspace

            DB_PASS: valorant_digital_workspace

    embanet-woocommerce-reporting-web:

        container_name: embanet-woocommerce-reporting-web

        image: softwareshinobi/embanet-woocommerce-reporting-web

        build: 

            context: web

            dockerfile: Dockerfile

        ports:

            - 8880:80

    embanet-woocommerce-reporting-docs:

        container_name: embanet-woocommerce-reporting-docs

        image: softwareshinobi/embanet-woocommerce-reporting-docs

        build: 

            context: docs

            dockerfile: Dockerfile

        ports:

            - 8882:80
